### PR TITLE
Update build configuration, use setuptools_scm

### PR DESCRIPTION
**Pull request by maxnoe**
- Remove setup.py
- Fix some issues in `pyproject.toml` (e.g. missing packages declaration, wrong extension for README)
- Remove version related files, use setuptools_scm instead.

### CODE REVIEW

**Comment by TjarkMiener** [comment]
Thanks a lot for this PR @maxnoe

**Comment by rcervinoucm** [comment]
Thanks for the PR @maxnoe. One question, removing setup.py will affect the release of the package in Conda?

**Comment by maxnoe** [comment]
@TjarkMiener @rcervinoucm Why is no CI running here?

**Review by rcervinoucm — APPROVED** [review]

**Comment by maxnoe** [comment]
@rcervinoucm I think this shouldn't have been merged in this state... you should have clicked on the button to start the CI workflow to check if the CI passes.

**Comment by rcervinoucm** [comment]
Hi Max, I have tried and the CI passes with the change s(I am working in a new branch and everything is ok), but you are right, I should have done that before

**Comment by maxnoe** [comment]
The release.yml workflow needs to be fixed, it is still using old stuff related to the old version handling and calls setup.py directly instead of using `python -m build`

**Comment by rcervinoucm** [comment]
I am working on that in a new branch, I will let you know when it is finished

**Pull request merged**
